name: CI Automation Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  robot-framework:
    name: Robot Framework Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Robot dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-jsonlibrary
          pip install selenium
          pip install webdriver-manager

      - name: Run Robot tests
        run: robot robot_tests
        continue-on-error: true


  selenium-pytest:
    name: Selenium Pytest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Pytest dependencies
        run: |
          pip install pytest
          pip install selenium
          pip install webdriver-manager

      - name: Run Pytest tests
        run: pytest selenium_tests
        continue-on-error: true


  playwright:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Playwright dependencies
        run: npm install
        working-directory: playwright_tests

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: playwright_tests

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: playwright_tests
        continue-on-error: true

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright_tests/playwright-report

        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
