name: CI - All Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  robot-framework-tests:
    name: Robot Framework Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Robot Framework dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-jsonlibrary
          pip install selenium
          pip install webdriver-manager

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Robot tests
        run: robot robot_tests


  selenium-pytest-tests:
    name: Selenium Pytest Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Pytest & Selenium
        run: |
          pip install --upgrade pip
          pip install pytest selenium webdriver-manager

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Pytest tests
        run: pytest selenium_tests


  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node dependencies
        working-directory: playwright_tests
        run: npm ci

      - name: Install Playwright browsers
        working-directory: playwright_tests
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: playwright_tests
        run: npx playwright test

